# NOTICE:
#
# Application name defined in TARGET has a corresponding QML filename.
# If name defined in TARGET is changed, the following needs to be done
# to match new name:
#   - corresponding QML filename must be changed
#   - desktop icon filename must be changed
#   - desktop filename must be changed
#   - icon definition filename in desktop file must be changed
#   - translation filenames have to be changed

# The name of your application
TARGET = harbour-sailfinder

# NOARCH support
#TEMPLATE = aux

CONFIG += sailfishapp

SOURCES += \
    qml/src/harbour-sailfinder.cpp

OTHER_FILES += qml/harbour-sailfinder.qml \
    qml/cover/CoverPage.qml \
    qml/pages/FirstPage.qml \
    translations/*.ts \
    harbour-sailfinder.desktop

SAILFISHAPP_ICONS = 86x86 108x108 128x128 256x256

# Enable translations support
CONFIG += sailfishapp_i18n
TRANSLATIONS += translations/harbour-sailfinder-nl_NL.ts

DISTFILES += \
    qml/pages/AboutPage.qml \
    qml/pages/AccountHeader.qml \
    qml/pages/CustomExpander.qml \
    qml/pages/CustomExpanderContent.qml \
    qml/pages/ExternalAccountsPage.qml \
    qml/pages/GlassButton.qml \
    qml/pages/GlassButtonEdit.qml \
    qml/pages/ImageGrid.qml \
    qml/pages/LoginProgress.qml \
    qml/pages/MainPage.qml \
    qml/pages/Matches.qml \
    qml/pages/MatchesDelegate.qml \
    qml/pages/MessagingBar.qml \
    qml/pages/MessagingHeader.qml \
    qml/pages/MessagingPage.qml \
    qml/pages/MessagingView.qml \
    qml/pages/NavigationBar.qml \
    qml/pages/NotificationManager.qml \
    qml/pages/OverlayMessage.qml \
    qml/pages/Profile.qml \
    qml/pages/Recommendations.qml \
    qml/pages/ReportPage.qml \
    qml/pages/SettingsPage.qml \
    qml/pages/Social.qml \
    qml/pages/TextLabel.qml \
    qml/pages/Toaster.qml \
    qml/pages/js/util.js \
    qml/pages/js/recs.js \
    qml/pages/js/profile.js \
    translations/harbour-sailfinder-nl_NL.ts \
    qml/pages/MatchesPopup.qml \
    qml/pages/LocationManager.qml \
    qml/pages/js/matches.js \
    qml/pages/ImageGridPlaceholder.qml \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:13:55.322231Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:15:18.715817Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:17:35.066125Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:18:02.996489Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:18:20.530484Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:19:40.778951Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:20:33.615722Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T08:22:11.673040Z.json \
    qml/backend/sailfinder/cache/updates/2017-02-10T14:21:25.769876Z.json \
    qml/backend/sailfinder/cache/updates/history.json \
    qml/backend/sailfinder/cache/updates/test.json \
    qml/backend/sailfinder/cache/52bdaf45167f67a95400096a.json \
    qml/backend/sailfinder/cache/532eb16fde8461d25400099f.json \
    qml/backend/sailfinder/cache/53333714b7d657c87e001d69.json \
    qml/backend/sailfinder/cache/56d422d94f10e5db60fe7823.json \
    qml/backend/sailfinder/cache/auth.json \
    qml/backend/sailfinder/cache/meta.json \
    qml/backend/sailfinder/cache/profile.json \
    qml/backend/sailfinder/cache/recommendations.json \
    qml/backend/sailfinder/cache/updates.tar.gz \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/_internal_utils.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/adapters.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/api.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/auth.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/certs.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/cookies.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/hooks.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/models.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/sessions.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/status_codes.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/structures.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/__pycache__/utils.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/big5freq.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/big5prober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/chardetect.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/chardistribution.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/charsetgroupprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/charsetprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/codingstatemachine.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/constants.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/cp949prober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/escprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/escsm.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/eucjpprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/euckrfreq.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/euckrprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/euctwfreq.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/euctwprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/gb2312freq.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/gb2312prober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/hebrewprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/jisfreq.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/jpcntx.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/langbulgarianmodel.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/langcyrillicmodel.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/langgreekmodel.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/langhebrewmodel.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/langhungarianmodel.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/langthaimodel.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/latin1prober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/mbcharsetprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/mbcsgroupprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/mbcssm.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/sbcharsetprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/sbcsgroupprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/sjisprober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/universaldetector.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__pycache__/utf8prober.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__pycache__/codec.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__pycache__/core.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__pycache__/idnadata.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__pycache__/intranges.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__pycache__/uts46data.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/_collections.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/connection.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/connectionpool.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/fields.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/filepost.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/poolmanager.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/request.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__pycache__/response.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__pycache__/appengine.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__pycache__/ntlmpool.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__pycache__/pyopenssl.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__pycache__/socks.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/__pycache__/ordered_dict.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/__pycache__/six.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/backports/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/_implementation.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/connection.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/request.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/response.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/retry.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/selectors.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/timeout.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/url.cpython-34.pyc \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/wait.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/__init__.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/__init__.cpython-35.pyc \
    qml/backend/sailfinder/__pycache__/authenticate.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/authenticate.cpython-35.pyc \
    qml/backend/sailfinder/__pycache__/cachemanager.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/constants.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/constants.cpython-35.pyc \
    qml/backend/sailfinder/__pycache__/filemanager.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/filemanager.cpython-35.pyc \
    qml/backend/sailfinder/__pycache__/logger.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/logger.cpython-35.pyc \
    qml/backend/sailfinder/__pycache__/network.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/network.cpython-35.pyc \
    qml/backend/sailfinder/__pycache__/sfos.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/sfos.cpython-35.pyc \
    qml/backend/sailfinder/__pycache__/tinder.cpython-34.pyc \
    qml/backend/sailfinder/__pycache__/tinder.cpython-35.pyc \
    qml/backend/sailfinder/__init__.pyc \
    qml/backend/sailfinder/authenticate.pyc \
    qml/backend/sailfinder/constants.pyc \
    qml/backend/sailfinder/facebook.pyc \
    qml/backend/sailfinder/filemanager.pyc \
    qml/backend/sailfinder/giphy.pyc \
    qml/backend/sailfinder/logger.pyc \
    qml/backend/sailfinder/network.pyc \
    qml/backend/sailfinder/sfos.pyc \
    qml/backend/sailfinder/tinder.pyc \
    qml/backend/lib/python3.4/site-packages/requests/cacert.pem \
    qml/backend/sailfinder/cache/logging/loggingOld.zip \
    qml/resources/images/icon-noimage.gif \
    qml/backend/sailfinder/cache/users/5299d5912021926b5200002c_32ed23d3-62f5-48da-a6e8-7b791d6609b5.jpg \
    qml/backend/sailfinder/cache/users/5299d5912021926b5200002c_76599b64-0501-408f-8fea-156fcdad5c77.jpg \
    qml/backend/sailfinder/cache/users/5299d5912021926b5200002c_a7dc82bc-5618-42b2-8328-bf100fbf0cb7.jpg \
    qml/backend/sailfinder/cache/users/52e429686c12e77517000196_605d2036-28fa-4de2-8de4-966070c4b6a2.jpg \
    qml/backend/sailfinder/cache/users/52e429686c12e77517000196_684a33bb-a05a-448e-8b2c-4e0186cacbbd.jpg \
    qml/backend/sailfinder/cache/users/52e429686c12e77517000196_aaad2398-e1df-4f96-8e94-bc9ef915da82.jpg \
    qml/backend/sailfinder/cache/users/52e429686c12e77517000196_bbc83eb2-3086-4008-8b0f-50f4b71f7328.jpg \
    qml/backend/sailfinder/cache/users/52e429686c12e77517000196_d61ea50a-bb7d-46d6-8aef-ca7bbcbb2e69.jpg \
    qml/backend/sailfinder/cache/users/52e429686c12e77517000196_e295996f-e6cc-4642-9641-660eedddf014.jpg \
    qml/backend/sailfinder/cache/users/535cc081dc50faff55002ab3_368183af-94c7-4d9e-84f0-2db55eb3cd06.jpg \
    qml/backend/sailfinder/cache/users/535cc081dc50faff55002ab3_5659fb76-5ae1-4c48-8245-20be48fba5fc.jpg \
    qml/backend/sailfinder/cache/users/535cc081dc50faff55002ab3_6ccdac61-2d41-40f5-88fb-c79dc19b5f83.jpg \
    qml/backend/sailfinder/cache/users/535cc081dc50faff55002ab3_9970075a-5a1a-436e-b70e-e8ae33b911cc.jpg \
    qml/backend/sailfinder/cache/users/538ce34c8be59cd34dcf5ce4_0db491aa-51b7-4684-a3f8-310f9c75beeb.jpg \
    qml/backend/sailfinder/cache/users/538ce34c8be59cd34dcf5ce4_1ac93757-f177-4951-8377-ef7d3f8f4304.jpg \
    qml/backend/sailfinder/cache/users/538ce34c8be59cd34dcf5ce4_27d9c399-3e8a-4f23-ae1f-912ed481e7bb.jpg \
    qml/backend/sailfinder/cache/users/538ce34c8be59cd34dcf5ce4_4738e1a8-1d7a-4c3c-9ccc-e6f313f437a2.jpg \
    qml/backend/sailfinder/cache/users/538ce34c8be59cd34dcf5ce4_a9cab37e-1489-4d44-8d41-a903c708af95.jpg \
    qml/backend/sailfinder/cache/users/54453a78bb8fd5421dcfec37_235fea90-a7e1-454f-86c9-571ed8b60bba.jpg \
    qml/backend/sailfinder/cache/users/54453a78bb8fd5421dcfec37_52c67170-5c0f-4fde-acd7-e2aa8e607315.jpg \
    qml/backend/sailfinder/cache/users/54453a78bb8fd5421dcfec37_8f1a6b5b-56a7-499e-b294-b550840a858b.jpg \
    qml/backend/sailfinder/cache/users/54453a78bb8fd5421dcfec37_f8617a65-d530-4d41-8b25-805ede973128.jpg \
    qml/backend/sailfinder/cache/users/54624fb0988d8c0f7d6eea24_042be5d8-613d-4c61-9e36-93657e5b6bd7.jpg \
    qml/backend/sailfinder/cache/users/54624fb0988d8c0f7d6eea24_0acf5cb0-aba3-470d-961b-01ee3677f576.jpg \
    qml/backend/sailfinder/cache/users/54624fb0988d8c0f7d6eea24_10344e0b-e937-49c3-b934-25e649c3f398.jpg \
    qml/backend/sailfinder/cache/users/54624fb0988d8c0f7d6eea24_9d19c7fd-bb14-416a-8f22-c446e74e021e.jpg \
    qml/backend/sailfinder/cache/users/54624fb0988d8c0f7d6eea24_a25b4070-a742-4811-83b8-9dd74d207bef.jpg \
    qml/backend/sailfinder/cache/users/54624fb0988d8c0f7d6eea24_a99eb414-a6c2-4815-9662-9e27f319ccee.jpg \
    qml/backend/sailfinder/cache/users/546501df119868b0246f5585_35b6bef1-7b88-46e2-831c-ddb3441b07d6.jpg \
    qml/backend/sailfinder/cache/users/546501df119868b0246f5585_6ffa8b3c-4722-4797-80f0-966dd163f93d.jpg \
    qml/backend/sailfinder/cache/users/546501df119868b0246f5585_b1f2bedd-2c1b-4729-91d6-e96d836cce88.jpg \
    qml/backend/sailfinder/cache/users/546501df119868b0246f5585_c03ebbc1-01d9-41de-8fee-65fa54aa7e21.jpg \
    qml/backend/sailfinder/cache/users/546501df119868b0246f5585_e0e033b9-3b85-468b-86de-bedb87376d57.jpg \
    qml/backend/sailfinder/cache/users/546501df119868b0246f5585_e603b502-06d9-4df5-8540-a8547a80c96a.jpg \
    qml/backend/sailfinder/cache/users/549c8c4f8681339a18ad6ea8_1ada0631-4ae6-4721-80fc-ced164e211ec.jpg \
    qml/backend/sailfinder/cache/users/549c8c4f8681339a18ad6ea8_354c87be-f58e-431e-8353-d3a1d01d09b6.jpg \
    qml/backend/sailfinder/cache/users/549c8c4f8681339a18ad6ea8_9791bf90-483f-4b6d-8731-1c07764633d3.jpg \
    qml/backend/sailfinder/cache/users/55259d7ad00821151fdec538_895a4f3f-82df-4e6e-8c53-2fe04a875df1.jpg \
    qml/backend/sailfinder/cache/users/55259d7ad00821151fdec538_afc5cbee-ff48-4b68-b711-42f327209ea2.jpg \
    qml/backend/sailfinder/cache/users/55b3ffb98c70c930074dd30e_034b56e0-9355-44c9-b421-9ec0bab54a92.jpg \
    qml/backend/sailfinder/cache/users/55b3ffb98c70c930074dd30e_537dc54f-a4bf-42fd-8ae2-eabce357c1c1.jpg \
    qml/backend/sailfinder/cache/users/55b3ffb98c70c930074dd30e_6d14f1de-ed68-462e-b64a-569bf0b2af81.jpg \
    qml/backend/sailfinder/cache/users/55b3ffb98c70c930074dd30e_c974468b-7171-4345-bdb6-2eeade9f3417.jpg \
    qml/backend/sailfinder/cache/users/55b3ffb98c70c930074dd30e_cf6b07a6-f6b2-4e87-8161-98c79d8992cb.jpg \
    qml/backend/sailfinder/cache/users/55b3ffb98c70c930074dd30e_ef65070e-405d-4cc9-86ba-becea0983ac3.jpg \
    qml/backend/sailfinder/cache/users/566409f441f67d0462e90356_246fb4eb-206b-434d-aa18-6a6fc5a152dc.jpg \
    qml/backend/sailfinder/cache/users/566409f441f67d0462e90356_53cadc10-f7a6-4851-8aeb-37ef7f768b8c.jpg \
    qml/backend/sailfinder/cache/users/566409f441f67d0462e90356_68d56d7a-04c5-47ca-ac76-13a651a12d3a.jpg \
    qml/backend/sailfinder/cache/users/566409f441f67d0462e90356_6bd2af65-8510-47bc-870a-0e33979175fe.jpg \
    qml/backend/sailfinder/cache/users/566409f441f67d0462e90356_9c18ab96-b42d-4b5d-8ac2-d951a39b2a95.jpg \
    qml/backend/sailfinder/cache/users/566409f441f67d0462e90356_d2d606e6-fceb-490d-9c34-539fda95c879.jpg \
    qml/backend/sailfinder/cache/users/5688722d30c19b4b2cf990d5_64cd6f6c-f79f-4f5c-9616-a260ea621810.jpg \
    qml/backend/sailfinder/cache/users/5688722d30c19b4b2cf990d5_6fe74011-179c-43da-abd2-f40f019c8f8d.jpg \
    qml/backend/sailfinder/cache/users/5688722d30c19b4b2cf990d5_8f1049ea-7ef5-48e2-9c12-ddd69dee36e9.jpg \
    qml/backend/sailfinder/cache/users/5688722d30c19b4b2cf990d5_df7f983e-c55d-44ba-8082-8b23c02bf035.jpg \
    qml/backend/sailfinder/cache/users/5688722d30c19b4b2cf990d5_ebef9cdb-e293-4489-acc0-ad3ac4fae91b.jpg \
    qml/backend/sailfinder/cache/users/572518cd0e93157313ca1eff_0a850e67-dd8f-4504-8018-60ea2f50bbad.jpg \
    qml/backend/sailfinder/cache/users/572518cd0e93157313ca1eff_13665f27-e883-40bf-8e7e-45726d7f760c.jpg \
    qml/backend/sailfinder/cache/users/572518cd0e93157313ca1eff_60f7529f-c81c-4cef-8bf8-648a3f0b4b99.jpg \
    qml/backend/sailfinder/cache/users/572518cd0e93157313ca1eff_6f003a4f-1795-4397-882a-9fac44cb12be.jpg \
    qml/backend/sailfinder/cache/users/572518cd0e93157313ca1eff_c3ae42aa-cf60-4a7d-8598-c166f8ac460e.jpg \
    qml/backend/sailfinder/cache/users/57362b6907ed91221236050a_08d07e78-1e25-45ac-96df-0d429bb04ca1.jpg \
    qml/backend/sailfinder/cache/users/57362b6907ed91221236050a_37e3278f-4ebb-4fba-86df-ac43747ba8f1.jpg \
    qml/backend/sailfinder/cache/users/5741d08864b900870b2158a1_0e2ba2b1-a594-47eb-83a9-625665d84741.jpg \
    qml/backend/sailfinder/cache/users/5741d08864b900870b2158a1_1324af88-2004-433e-82be-aa2115e43b95.jpg \
    qml/backend/sailfinder/cache/users/5741d08864b900870b2158a1_1550750f-801e-4e76-9e63-4330ad232bff.jpg \
    qml/backend/sailfinder/cache/users/5741d08864b900870b2158a1_423ba728-0489-42e6-9fcf-b637294585d2.jpg \
    qml/backend/sailfinder/cache/users/5741d08864b900870b2158a1_e9cfa034-14ca-4dde-82ec-639765583996.jpg \
    qml/backend/sailfinder/cache/users/5741d08864b900870b2158a1_fc4b6fc3-dc37-4cd7-aa9c-1c8b78e0d8ce.jpg \
    qml/backend/sailfinder/cache/users/578e91925e3aaee309f6c274_6e36435e-b70f-495c-baa0-108501f32978.jpg \
    qml/backend/sailfinder/cache/users/578e91925e3aaee309f6c274_85e03e76-4dd6-4403-8b03-744e5ab68e10.jpg \
    qml/backend/sailfinder/cache/users/578e91925e3aaee309f6c274_864d140c-29d3-407d-85f3-83fb45c1aac7.jpg \
    qml/backend/sailfinder/cache/users/578e91925e3aaee309f6c274_ac8220fe-adba-4ab0-87a1-ef5c88540a90.jpg \
    qml/backend/sailfinder/cache/users/579646ace73639b3248fe49e_138bad89-0a48-4328-8541-6341dfcff893.jpg \
    qml/backend/sailfinder/cache/users/579646ace73639b3248fe49e_8ae58d5b-8de2-4e84-841e-e5447a1472ec.jpg \
    qml/backend/sailfinder/cache/users/579646ace73639b3248fe49e_ac862685-dd78-46a0-a1fc-82bc86efbb83.jpg \
    qml/backend/sailfinder/cache/users/579646ace73639b3248fe49e_d9472f37-1319-4729-8893-f650da40caaa.jpg \
    qml/backend/sailfinder/cache/users/579646ace73639b3248fe49e_d9df67dd-e65b-42dd-81a3-097e8d83d1b2.jpg \
    qml/backend/sailfinder/cache/users/579646ace73639b3248fe49e_ff6739de-1a2d-4336-8bce-78f58ebef453.jpg \
    qml/backend/sailfinder/cache/users/57c6c596d74fd74a5a394077_02e6fbd8-39a7-48fd-b2f7-ac70266b829b.jpg \
    qml/backend/sailfinder/cache/users/57c6c596d74fd74a5a394077_5a264d15-c1fe-4991-a1bc-7f1e9096e547.jpg \
    qml/backend/sailfinder/cache/users/57c6c596d74fd74a5a394077_92eed06e-c4d2-4980-820e-e740d58b48f5.jpg \
    qml/backend/sailfinder/cache/users/57c6c596d74fd74a5a394077_e9586805-731d-4bbc-8cf6-5a20ffee21c4.jpg \
    qml/backend/sailfinder/cache/users/57c6c596d74fd74a5a394077_f04e6558-92a7-4bac-876f-7d053c1b6d30.jpg \
    qml/backend/sailfinder/cache/users/57c6c596d74fd74a5a394077_f0a7b3a9-9b97-455b-8753-7af4a037af87.jpg \
    qml/backend/sailfinder/cache/users/58250dca82e9748b440c530b_09ef5f57-b8da-4a33-9bb1-906b042b577d.jpg \
    qml/backend/sailfinder/cache/users/58250dca82e9748b440c530b_676667da-89d0-4532-a8fa-92291811cd6e.jpg \
    qml/backend/sailfinder/cache/users/58250dca82e9748b440c530b_6bd29a0c-0a1c-44b2-8bb3-e48b126d92a4.jpg \
    qml/backend/sailfinder/cache/users/58250dca82e9748b440c530b_7e4bc062-80d1-47ea-882b-f28acaaba8d6.jpg \
    qml/backend/sailfinder/cache/users/58250dca82e9748b440c530b_85ae5c37-dd42-4969-8eff-e22ac8c983ef.jpg \
    qml/backend/sailfinder/cache/users/58250dca82e9748b440c530b_ba6c82f4-d845-4a96-b199-eb172013b484.jpg \
    qml/backend/sailfinder/cache/users/584c4a1c962e47e3095cda72_02b72846-63fd-48fc-8e7a-8f1463169721.jpg \
    qml/backend/sailfinder/cache/users/584c4a1c962e47e3095cda72_946ef3c6-1829-45dd-85df-739cbab44a79.jpg \
    qml/backend/sailfinder/cache/users/584c4a1c962e47e3095cda72_d591403d-859d-479b-8121-7f1c951903e6.jpg \
    qml/backend/sailfinder/cache/users/584c4a1c962e47e3095cda72_d6b532ea-a57f-450b-8e20-07d6f2203729.jpg \
    qml/backend/sailfinder/cache/users/584c4a1c962e47e3095cda72_e411cd46-75d2-4c6c-85ed-eeddb2e687f5.jpg \
    qml/backend/sailfinder/cache/users/587265e7beaa656c4f3da5d1_11cdaef3-cd6a-45f8-8415-ea9ca162af47.jpg \
    qml/backend/sailfinder/cache/users/587265e7beaa656c4f3da5d1_96792c5a-a599-4caa-bc7e-5de779620c6b.jpg \
    qml/backend/sailfinder/cache/users/587265e7beaa656c4f3da5d1_ccad79dd-9b21-477e-a767-07a4190774ba.jpg \
    qml/backend/sailfinder/cache/users/587265e7beaa656c4f3da5d1_d601ec7d-a6ac-4afa-805e-fd7ed16a77c6.jpg \
    qml/backend/sailfinder/cache/users/587265e7beaa656c4f3da5d1_fc653448-3604-41ca-8adc-11fb924c6606.jpg \
    qml/backend/sailfinder/cache/users/58791169e815451a028f553b_4abc2e3f-24f9-47df-9f77-96967045b746.jpg \
    qml/backend/sailfinder/cache/users/587e7f853525d3de04fea5f7_2f03f29d-cd32-4cf0-a347-07be61b01db7.jpg \
    qml/backend/sailfinder/cache/users/587e7f853525d3de04fea5f7_53368185-d9e3-46cb-9484-cb10645d39c9.jpg \
    qml/backend/sailfinder/cache/users/587e7f853525d3de04fea5f7_75f16d6b-7b6a-435e-8338-105a93c17573.jpg \
    qml/backend/sailfinder/cache/users/587e7f853525d3de04fea5f7_cb84467e-7ed8-4e49-97c9-eea67962db54.jpg \
    qml/backend/sailfinder/cache/users/58811e4a6a586d562514abf3_9f9e2cfb-18dd-427b-8a66-42e25059e11b.jpg \
    qml/backend/sailfinder/cache/users/58811e4a6a586d562514abf3_ef8b596d-fc9b-45b4-8abb-64a310f38b03.jpg \
    qml/backend/sailfinder/cache/users/5887b2b741d3400f6da8a927_5c5ed6ba-5bb8-46dc-aedf-305b0b92d452.jpg \
    qml/backend/sailfinder/cache/users/5887b2b741d3400f6da8a927_8d10f87c-6496-478d-90bd-6b237b79cf0b.jpg \
    qml/backend/sailfinder/cache/530394626c74651319002036_51d6cba8-6d24-414d-97e1-4c0bbf3daa02.jpg \
    qml/backend/sailfinder/cache/5875ee47f848cfa224ef7f41_dac403fb-3c2e-441a-9761-855b078a4ae2.jpg \
    qml/backend/sailfinder/data/test.jpg \
    qml/resources/images/account-logo.png \
    qml/resources/images/dislike.png \
    qml/resources/images/icon-addimage.png \
    qml/resources/images/icon-bio.png \
    qml/resources/images/icon-code.png \
    qml/resources/images/icon-edit.png \
    qml/resources/images/icon-fontawesome.png \
    qml/resources/images/icon-friends.png \
    qml/resources/images/icon-giphy.png \
    qml/resources/images/icon-github.png \
    qml/resources/images/icon-gitlab.png \
    qml/resources/images/icon-instagram.png \
    qml/resources/images/icon-job.png \
    qml/resources/images/icon-location.png \
    qml/resources/images/icon-matches.png \
    qml/resources/images/icon-more.png \
    qml/resources/images/icon-noimage.png \
    qml/resources/images/icon-notifications.png \
    qml/resources/images/icon-paypal.png \
    qml/resources/images/icon-profile.png \
    qml/resources/images/icon-recs.png \
    qml/resources/images/icon-refresh.png \
    qml/resources/images/icon-school.png \
    qml/resources/images/icon-search.png \
    qml/resources/images/icon-send.png \
    qml/resources/images/icon-share.png \
    qml/resources/images/icon-social.png \
    qml/resources/images/icon-spotify.png \
    qml/resources/images/image-placeholder.png \
    qml/resources/images/launcher-logo.png \
    qml/resources/images/like.png \
    qml/resources/images/superlike.png \
    qml/backend/lib/python3.4/site-packages/requests-2.13.0-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/python3.4/site-packages/requests-2.13.0-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/python3.4/site-packages/requests-2.13.0-py3.4.egg-info/not-zip-safe \
    qml/backend/lib/python3.4/site-packages/requests-2.13.0-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/python3.4/site-packages/requests-2.13.0-py3.4.egg-info/requires.txt \
    qml/backend/lib/python3.4/site-packages/requests-2.13.0-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/python3.4/site-packages/requests-2.13.0-py3.4.egg-info/top_level.txt \
    qml/backend/sailfinder/cache/facebook_token.txt \
    qml/backend/sailfinder/connman-data/NetworkName \
    qml/backend/sailfinder/connman-data/NetworkState \
    qml/backend/sailfinder/connman-data/NetworkType \
    qml/backend/sailfinder/connman-data/SignalStrength \
    qml/backend/sailfinder/connman-data/Tethering \
    qml/backend/sailfinder/connman-data/TrafficIn \
    qml/backend/sailfinder/connman-data/TrafficOut \
    qml/resources/images/sources.txt \
    qml/resources/notifications/x-habour.sailfinder.notify.conf \
    qml/backend/sailfinder/cache/logging/2017-02-06T16:56:14.log \
    qml/backend/sailfinder/cache/logging/2017-02-08T07:41:53.log \
    qml/backend/sailfinder/cache/logging/2017-02-10T08:08:24.log \
    qml/backend/sailfinder/cache/logging/2017-02-10T14:21:24.log \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/big5freq.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/big5prober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/chardetect.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/chardistribution.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/charsetgroupprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/charsetprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/codingstatemachine.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/compat.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/constants.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/cp949prober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/escprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/escsm.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/eucjpprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/euckrfreq.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/euckrprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/euctwfreq.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/euctwprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/gb2312freq.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/gb2312prober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/hebrewprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/jisfreq.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/jpcntx.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/langbulgarianmodel.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/langcyrillicmodel.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/langgreekmodel.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/langhebrewmodel.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/langhungarianmodel.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/langthaimodel.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/latin1prober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/mbcharsetprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/mbcsgroupprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/mbcssm.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/sbcharsetprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/sbcsgroupprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/sjisprober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/universaldetector.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/chardet/utf8prober.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/codec.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/compat.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/core.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/idnadata.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/intranges.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/idna/uts46data.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/appengine.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/ntlmpool.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/pyopenssl.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/contrib/socks.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/backports/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/ordered_dict.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/request.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/response.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/selectors.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/timeout.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/url.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/util/wait.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/_collections.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/connection.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/exceptions.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/fields.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/filepost.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/poolmanager.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/request.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/urllib3/response.py \
    qml/backend/lib/python3.4/site-packages/requests/packages/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/__init__.py \
    qml/backend/lib/python3.4/site-packages/requests/_internal_utils.py \
    qml/backend/lib/python3.4/site-packages/requests/adapters.py \
    qml/backend/lib/python3.4/site-packages/requests/api.py \
    qml/backend/lib/python3.4/site-packages/requests/auth.py \
    qml/backend/lib/python3.4/site-packages/requests/certs.py \
    qml/backend/lib/python3.4/site-packages/requests/compat.py \
    qml/backend/lib/python3.4/site-packages/requests/cookies.py \
    qml/backend/lib/python3.4/site-packages/requests/exceptions.py \
    qml/backend/lib/python3.4/site-packages/requests/hooks.py \
    qml/backend/lib/python3.4/site-packages/requests/models.py \
    qml/backend/lib/python3.4/site-packages/requests/sessions.py \
    qml/backend/lib/python3.4/site-packages/requests/status_codes.py \
    qml/backend/lib/python3.4/site-packages/requests/structures.py \
    qml/backend/lib/python3.4/site-packages/requests/utils.py \
    qml/backend/sailfinder/__init__.py \
    qml/backend/sailfinder/authenticate.py \
    qml/backend/sailfinder/cachemanager.py \
    qml/backend/sailfinder/constants.py \
    qml/backend/sailfinder/facebook.py \
    qml/backend/sailfinder/filemanager.py \
    qml/backend/sailfinder/giphy.py \
    qml/backend/sailfinder/logger.py \
    qml/backend/sailfinder/network.py \
    qml/backend/sailfinder/sfos.py \
    qml/backend/sailfinder/spotify.py \
    qml/backend/sailfinder/tinder.py \
    qml/backend/__init__.py \
    qml/backend/app.py \
    qml/backend/lib/armv7l/werkzeug/debug/shared/debugger.js \
    qml/backend/lib/armv7l/werkzeug/debug/shared/jquery.js \
    qml/backend/lib/armv7l/werkzeug/debug/shared/ubuntu.ttf \
    qml/backend/lib/armv7l/__pycache__/six.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/__pycache__/1631353.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/__pycache__/dammit.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/__pycache__/diagnose.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/__pycache__/element.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/__pycache__/testing.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/builder/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/builder/__pycache__/_html5lib.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/builder/__pycache__/_htmlparser.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/builder/__pycache__/_lxml.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/test_builder_registry.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/test_docs.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/test_html5lib.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/test_htmlparser.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/test_lxml.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/test_soup.cpython-34.pyc \
    qml/backend/lib/armv7l/bs4/tests/__pycache__/test_tree.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/_internal_utils.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/adapters.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/api.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/auth.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/certs.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/cookies.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/hooks.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/models.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/sessions.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/status_codes.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/structures.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/__pycache__/utils.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/big5freq.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/big5prober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/chardetect.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/chardistribution.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/charsetgroupprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/charsetprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/codingstatemachine.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/constants.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/cp949prober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/escprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/escsm.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/eucjpprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/euckrfreq.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/euckrprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/euctwfreq.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/euctwprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/gb2312freq.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/gb2312prober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/hebrewprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/jisfreq.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/jpcntx.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/langbulgarianmodel.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/langcyrillicmodel.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/langgreekmodel.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/langhebrewmodel.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/langhungarianmodel.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/langthaimodel.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/latin1prober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/mbcharsetprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/mbcsgroupprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/mbcssm.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/sbcharsetprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/sbcsgroupprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/sjisprober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/universaldetector.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/chardet/__pycache__/utf8prober.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/idna/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/idna/__pycache__/codec.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/idna/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/idna/__pycache__/core.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/idna/__pycache__/idnadata.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/idna/__pycache__/intranges.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/idna/__pycache__/uts46data.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/_collections.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/connection.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/connectionpool.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/fields.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/filepost.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/poolmanager.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/request.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/__pycache__/response.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/__pycache__/appengine.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/__pycache__/ntlmpool.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/__pycache__/pyopenssl.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/__pycache__/socks.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/__pycache__/ordered_dict.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/__pycache__/six.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/backports/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/backports/__pycache__/makefile.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/_implementation.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/connection.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/request.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/response.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/retry.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/selectors.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/timeout.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/url.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__pycache__/wait.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/browser.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/cache.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/helpers.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/ordereddict.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/__pycache__/responses.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/forms/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/forms/__pycache__/fields.cpython-34.pyc \
    qml/backend/lib/armv7l/robobrowser/forms/__pycache__/form.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/_compat.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/_internal.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/_reloader.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/datastructures.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/filesystem.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/formparser.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/http.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/local.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/posixemulation.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/routing.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/script.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/security.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/serving.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/test.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/testapp.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/urls.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/useragents.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/utils.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/wrappers.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/__pycache__/wsgi.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/atom.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/cache.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/fixers.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/iterio.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/jsrouting.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/limiter.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/lint.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/profiler.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/securecookie.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/sessions.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/testtools.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/contrib/__pycache__/wrappers.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/debug/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/debug/__pycache__/console.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/debug/__pycache__/repr.cpython-34.pyc \
    qml/backend/lib/armv7l/werkzeug/debug/__pycache__/tbtools.cpython-34.pyc \
    qml/backend/lib/armv7l/requests/cacert.pem \
    qml/backend/lib/armv7l/werkzeug/debug/shared/console.png \
    qml/backend/lib/armv7l/werkzeug/debug/shared/less.png \
    qml/backend/lib/armv7l/werkzeug/debug/shared/more.png \
    qml/backend/lib/armv7l/werkzeug/debug/shared/source.png \
    qml/backend/lib/armv7l/werkzeug/debug/shared/style.css \
    qml/backend/lib/armv7l/beautifulsoup4-4.5.3-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/armv7l/beautifulsoup4-4.5.3-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/armv7l/beautifulsoup4-4.5.3-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/armv7l/beautifulsoup4-4.5.3-py3.4.egg-info/requires.txt \
    qml/backend/lib/armv7l/beautifulsoup4-4.5.3-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/armv7l/beautifulsoup4-4.5.3-py3.4.egg-info/top_level.txt \
    qml/backend/lib/armv7l/requests-2.13.0-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/armv7l/requests-2.13.0-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/armv7l/requests-2.13.0-py3.4.egg-info/not-zip-safe \
    qml/backend/lib/armv7l/requests-2.13.0-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/armv7l/requests-2.13.0-py3.4.egg-info/requires.txt \
    qml/backend/lib/armv7l/requests-2.13.0-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/armv7l/requests-2.13.0-py3.4.egg-info/top_level.txt \
    qml/backend/lib/armv7l/robobrowser-0.5.3-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/armv7l/robobrowser-0.5.3-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/armv7l/robobrowser-0.5.3-py3.4.egg-info/not-zip-safe \
    qml/backend/lib/armv7l/robobrowser-0.5.3-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/armv7l/robobrowser-0.5.3-py3.4.egg-info/requires.txt \
    qml/backend/lib/armv7l/robobrowser-0.5.3-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/armv7l/robobrowser-0.5.3-py3.4.egg-info/top_level.txt \
    qml/backend/lib/armv7l/six-1.10.0-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/armv7l/six-1.10.0-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/armv7l/six-1.10.0-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/armv7l/six-1.10.0-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/armv7l/six-1.10.0-py3.4.egg-info/top_level.txt \
    qml/backend/lib/armv7l/werkzeug/debug/shared/FONT_LICENSE \
    qml/backend/lib/armv7l/Werkzeug-0.11.15-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/armv7l/Werkzeug-0.11.15-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/armv7l/Werkzeug-0.11.15-py3.4.egg-info/not-zip-safe \
    qml/backend/lib/armv7l/Werkzeug-0.11.15-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/armv7l/Werkzeug-0.11.15-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/armv7l/Werkzeug-0.11.15-py3.4.egg-info/top_level.txt \
    qml/backend/lib/armv7l/bs4/builder/__init__.py \
    qml/backend/lib/armv7l/bs4/builder/_html5lib.py \
    qml/backend/lib/armv7l/bs4/builder/_htmlparser.py \
    qml/backend/lib/armv7l/bs4/builder/_lxml.py \
    qml/backend/lib/armv7l/bs4/tests/__init__.py \
    qml/backend/lib/armv7l/bs4/tests/test_builder_registry.py \
    qml/backend/lib/armv7l/bs4/tests/test_docs.py \
    qml/backend/lib/armv7l/bs4/tests/test_html5lib.py \
    qml/backend/lib/armv7l/bs4/tests/test_htmlparser.py \
    qml/backend/lib/armv7l/bs4/tests/test_lxml.py \
    qml/backend/lib/armv7l/bs4/tests/test_soup.py \
    qml/backend/lib/armv7l/bs4/tests/test_tree.py \
    qml/backend/lib/armv7l/bs4/1631353.py \
    qml/backend/lib/armv7l/bs4/__init__.py \
    qml/backend/lib/armv7l/bs4/dammit.py \
    qml/backend/lib/armv7l/bs4/diagnose.py \
    qml/backend/lib/armv7l/bs4/element.py \
    qml/backend/lib/armv7l/bs4/testing.py \
    qml/backend/lib/armv7l/requests/packages/chardet/__init__.py \
    qml/backend/lib/armv7l/requests/packages/chardet/big5freq.py \
    qml/backend/lib/armv7l/requests/packages/chardet/big5prober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/chardetect.py \
    qml/backend/lib/armv7l/requests/packages/chardet/chardistribution.py \
    qml/backend/lib/armv7l/requests/packages/chardet/charsetgroupprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/charsetprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/codingstatemachine.py \
    qml/backend/lib/armv7l/requests/packages/chardet/compat.py \
    qml/backend/lib/armv7l/requests/packages/chardet/constants.py \
    qml/backend/lib/armv7l/requests/packages/chardet/cp949prober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/escprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/escsm.py \
    qml/backend/lib/armv7l/requests/packages/chardet/eucjpprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/euckrfreq.py \
    qml/backend/lib/armv7l/requests/packages/chardet/euckrprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/euctwfreq.py \
    qml/backend/lib/armv7l/requests/packages/chardet/euctwprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/gb2312freq.py \
    qml/backend/lib/armv7l/requests/packages/chardet/gb2312prober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/hebrewprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/jisfreq.py \
    qml/backend/lib/armv7l/requests/packages/chardet/jpcntx.py \
    qml/backend/lib/armv7l/requests/packages/chardet/langbulgarianmodel.py \
    qml/backend/lib/armv7l/requests/packages/chardet/langcyrillicmodel.py \
    qml/backend/lib/armv7l/requests/packages/chardet/langgreekmodel.py \
    qml/backend/lib/armv7l/requests/packages/chardet/langhebrewmodel.py \
    qml/backend/lib/armv7l/requests/packages/chardet/langhungarianmodel.py \
    qml/backend/lib/armv7l/requests/packages/chardet/langthaimodel.py \
    qml/backend/lib/armv7l/requests/packages/chardet/latin1prober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/mbcharsetprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/mbcsgroupprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/mbcssm.py \
    qml/backend/lib/armv7l/requests/packages/chardet/sbcharsetprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/sbcsgroupprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/sjisprober.py \
    qml/backend/lib/armv7l/requests/packages/chardet/universaldetector.py \
    qml/backend/lib/armv7l/requests/packages/chardet/utf8prober.py \
    qml/backend/lib/armv7l/requests/packages/idna/__init__.py \
    qml/backend/lib/armv7l/requests/packages/idna/codec.py \
    qml/backend/lib/armv7l/requests/packages/idna/compat.py \
    qml/backend/lib/armv7l/requests/packages/idna/core.py \
    qml/backend/lib/armv7l/requests/packages/idna/idnadata.py \
    qml/backend/lib/armv7l/requests/packages/idna/intranges.py \
    qml/backend/lib/armv7l/requests/packages/idna/uts46data.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/__init__.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/appengine.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/ntlmpool.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/pyopenssl.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/contrib/socks.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/backports/__init__.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/backports/makefile.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/__init__.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/ordered_dict.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/packages/six.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/__init__.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/connection.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/request.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/response.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/retry.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/selectors.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/ssl_.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/timeout.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/url.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/util/wait.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/__init__.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/_collections.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/connection.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/connectionpool.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/exceptions.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/fields.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/filepost.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/poolmanager.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/request.py \
    qml/backend/lib/armv7l/requests/packages/urllib3/response.py \
    qml/backend/lib/armv7l/requests/packages/__init__.py \
    qml/backend/lib/armv7l/requests/__init__.py \
    qml/backend/lib/armv7l/requests/_internal_utils.py \
    qml/backend/lib/armv7l/requests/adapters.py \
    qml/backend/lib/armv7l/requests/api.py \
    qml/backend/lib/armv7l/requests/auth.py \
    qml/backend/lib/armv7l/requests/certs.py \
    qml/backend/lib/armv7l/requests/compat.py \
    qml/backend/lib/armv7l/requests/cookies.py \
    qml/backend/lib/armv7l/requests/exceptions.py \
    qml/backend/lib/armv7l/requests/hooks.py \
    qml/backend/lib/armv7l/requests/models.py \
    qml/backend/lib/armv7l/requests/sessions.py \
    qml/backend/lib/armv7l/requests/status_codes.py \
    qml/backend/lib/armv7l/requests/structures.py \
    qml/backend/lib/armv7l/requests/utils.py \
    qml/backend/lib/armv7l/robobrowser/forms/__init__.py \
    qml/backend/lib/armv7l/robobrowser/forms/fields.py \
    qml/backend/lib/armv7l/robobrowser/forms/form.py \
    qml/backend/lib/armv7l/robobrowser/__init__.py \
    qml/backend/lib/armv7l/robobrowser/browser.py \
    qml/backend/lib/armv7l/robobrowser/cache.py \
    qml/backend/lib/armv7l/robobrowser/compat.py \
    qml/backend/lib/armv7l/robobrowser/exceptions.py \
    qml/backend/lib/armv7l/robobrowser/helpers.py \
    qml/backend/lib/armv7l/robobrowser/ordereddict.py \
    qml/backend/lib/armv7l/robobrowser/responses.py \
    qml/backend/lib/armv7l/werkzeug/contrib/__init__.py \
    qml/backend/lib/armv7l/werkzeug/contrib/atom.py \
    qml/backend/lib/armv7l/werkzeug/contrib/cache.py \
    qml/backend/lib/armv7l/werkzeug/contrib/fixers.py \
    qml/backend/lib/armv7l/werkzeug/contrib/iterio.py \
    qml/backend/lib/armv7l/werkzeug/contrib/jsrouting.py \
    qml/backend/lib/armv7l/werkzeug/contrib/limiter.py \
    qml/backend/lib/armv7l/werkzeug/contrib/lint.py \
    qml/backend/lib/armv7l/werkzeug/contrib/profiler.py \
    qml/backend/lib/armv7l/werkzeug/contrib/securecookie.py \
    qml/backend/lib/armv7l/werkzeug/contrib/sessions.py \
    qml/backend/lib/armv7l/werkzeug/contrib/testtools.py \
    qml/backend/lib/armv7l/werkzeug/contrib/wrappers.py \
    qml/backend/lib/armv7l/werkzeug/debug/__init__.py \
    qml/backend/lib/armv7l/werkzeug/debug/console.py \
    qml/backend/lib/armv7l/werkzeug/debug/repr.py \
    qml/backend/lib/armv7l/werkzeug/debug/tbtools.py \
    qml/backend/lib/armv7l/werkzeug/__init__.py \
    qml/backend/lib/armv7l/werkzeug/_compat.py \
    qml/backend/lib/armv7l/werkzeug/_internal.py \
    qml/backend/lib/armv7l/werkzeug/_reloader.py \
    qml/backend/lib/armv7l/werkzeug/datastructures.py \
    qml/backend/lib/armv7l/werkzeug/exceptions.py \
    qml/backend/lib/armv7l/werkzeug/filesystem.py \
    qml/backend/lib/armv7l/werkzeug/formparser.py \
    qml/backend/lib/armv7l/werkzeug/http.py \
    qml/backend/lib/armv7l/werkzeug/local.py \
    qml/backend/lib/armv7l/werkzeug/posixemulation.py \
    qml/backend/lib/armv7l/werkzeug/routing.py \
    qml/backend/lib/armv7l/werkzeug/script.py \
    qml/backend/lib/armv7l/werkzeug/security.py \
    qml/backend/lib/armv7l/werkzeug/serving.py \
    qml/backend/lib/armv7l/werkzeug/test.py \
    qml/backend/lib/armv7l/werkzeug/testapp.py \
    qml/backend/lib/armv7l/werkzeug/urls.py \
    qml/backend/lib/armv7l/werkzeug/useragents.py \
    qml/backend/lib/armv7l/werkzeug/utils.py \
    qml/backend/lib/armv7l/werkzeug/wrappers.py \
    qml/backend/lib/armv7l/werkzeug/wsgi.py \
    qml/backend/lib/armv7l/six.py \
    qml/backend/lib/i486/werkzeug/debug/shared/debugger.js \
    qml/backend/lib/i486/werkzeug/debug/shared/jquery.js \
    qml/backend/lib/i486/werkzeug/debug/shared/ubuntu.ttf \
    qml/backend/lib/i486/__pycache__/six.cpython-34.pyc \
    qml/backend/lib/i486/bs4/__pycache__/1631353.cpython-34.pyc \
    qml/backend/lib/i486/bs4/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/bs4/__pycache__/dammit.cpython-34.pyc \
    qml/backend/lib/i486/bs4/__pycache__/diagnose.cpython-34.pyc \
    qml/backend/lib/i486/bs4/__pycache__/element.cpython-34.pyc \
    qml/backend/lib/i486/bs4/__pycache__/testing.cpython-34.pyc \
    qml/backend/lib/i486/bs4/builder/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/bs4/builder/__pycache__/_html5lib.cpython-34.pyc \
    qml/backend/lib/i486/bs4/builder/__pycache__/_htmlparser.cpython-34.pyc \
    qml/backend/lib/i486/bs4/builder/__pycache__/_lxml.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/test_builder_registry.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/test_docs.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/test_html5lib.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/test_htmlparser.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/test_lxml.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/test_soup.cpython-34.pyc \
    qml/backend/lib/i486/bs4/tests/__pycache__/test_tree.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/_internal_utils.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/adapters.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/api.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/auth.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/certs.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/cookies.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/hooks.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/models.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/sessions.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/status_codes.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/structures.cpython-34.pyc \
    qml/backend/lib/i486/requests/__pycache__/utils.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/big5freq.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/big5prober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/chardetect.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/chardistribution.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/charsetgroupprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/charsetprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/codingstatemachine.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/constants.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/cp949prober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/escprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/escsm.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/eucjpprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/euckrfreq.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/euckrprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/euctwfreq.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/euctwprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/gb2312freq.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/gb2312prober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/hebrewprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/jisfreq.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/jpcntx.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/langbulgarianmodel.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/langcyrillicmodel.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/langgreekmodel.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/langhebrewmodel.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/langhungarianmodel.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/langthaimodel.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/latin1prober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/mbcharsetprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/mbcsgroupprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/mbcssm.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/sbcharsetprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/sbcsgroupprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/sjisprober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/universaldetector.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/chardet/__pycache__/utf8prober.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/idna/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/idna/__pycache__/codec.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/idna/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/idna/__pycache__/core.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/idna/__pycache__/idnadata.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/idna/__pycache__/intranges.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/idna/__pycache__/uts46data.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/_collections.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/connection.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/connectionpool.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/fields.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/filepost.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/poolmanager.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/request.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/__pycache__/response.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/__pycache__/appengine.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/__pycache__/ntlmpool.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/__pycache__/pyopenssl.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/__pycache__/socks.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/packages/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/packages/__pycache__/ordered_dict.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/packages/__pycache__/six.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/packages/backports/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/packages/backports/__pycache__/makefile.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/_implementation.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/connection.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/request.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/response.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/retry.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/selectors.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/timeout.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/url.cpython-34.pyc \
    qml/backend/lib/i486/requests/packages/urllib3/util/__pycache__/wait.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/browser.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/cache.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/compat.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/helpers.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/ordereddict.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/__pycache__/responses.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/forms/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/forms/__pycache__/fields.cpython-34.pyc \
    qml/backend/lib/i486/robobrowser/forms/__pycache__/form.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/_compat.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/_internal.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/_reloader.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/datastructures.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/exceptions.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/filesystem.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/formparser.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/http.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/local.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/posixemulation.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/routing.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/script.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/security.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/serving.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/test.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/testapp.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/urls.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/useragents.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/utils.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/wrappers.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/__pycache__/wsgi.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/atom.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/cache.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/fixers.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/iterio.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/jsrouting.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/limiter.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/lint.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/profiler.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/securecookie.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/sessions.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/testtools.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/contrib/__pycache__/wrappers.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/debug/__pycache__/__init__.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/debug/__pycache__/console.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/debug/__pycache__/repr.cpython-34.pyc \
    qml/backend/lib/i486/werkzeug/debug/__pycache__/tbtools.cpython-34.pyc \
    qml/backend/lib/i486/requests/cacert.pem \
    qml/backend/lib/i486/werkzeug/debug/shared/console.png \
    qml/backend/lib/i486/werkzeug/debug/shared/less.png \
    qml/backend/lib/i486/werkzeug/debug/shared/more.png \
    qml/backend/lib/i486/werkzeug/debug/shared/source.png \
    qml/backend/lib/i486/werkzeug/debug/shared/style.css \
    qml/backend/lib/i486/beautifulsoup4-4.5.3-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/i486/beautifulsoup4-4.5.3-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/i486/beautifulsoup4-4.5.3-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/i486/beautifulsoup4-4.5.3-py3.4.egg-info/requires.txt \
    qml/backend/lib/i486/beautifulsoup4-4.5.3-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/i486/beautifulsoup4-4.5.3-py3.4.egg-info/top_level.txt \
    qml/backend/lib/i486/requests-2.13.0-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/i486/requests-2.13.0-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/i486/requests-2.13.0-py3.4.egg-info/not-zip-safe \
    qml/backend/lib/i486/requests-2.13.0-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/i486/requests-2.13.0-py3.4.egg-info/requires.txt \
    qml/backend/lib/i486/requests-2.13.0-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/i486/requests-2.13.0-py3.4.egg-info/top_level.txt \
    qml/backend/lib/i486/robobrowser-0.5.3-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/i486/robobrowser-0.5.3-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/i486/robobrowser-0.5.3-py3.4.egg-info/not-zip-safe \
    qml/backend/lib/i486/robobrowser-0.5.3-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/i486/robobrowser-0.5.3-py3.4.egg-info/requires.txt \
    qml/backend/lib/i486/robobrowser-0.5.3-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/i486/robobrowser-0.5.3-py3.4.egg-info/top_level.txt \
    qml/backend/lib/i486/six-1.10.0-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/i486/six-1.10.0-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/i486/six-1.10.0-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/i486/six-1.10.0-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/i486/six-1.10.0-py3.4.egg-info/top_level.txt \
    qml/backend/lib/i486/werkzeug/debug/shared/FONT_LICENSE \
    qml/backend/lib/i486/Werkzeug-0.11.15-py3.4.egg-info/dependency_links.txt \
    qml/backend/lib/i486/Werkzeug-0.11.15-py3.4.egg-info/installed-files.txt \
    qml/backend/lib/i486/Werkzeug-0.11.15-py3.4.egg-info/not-zip-safe \
    qml/backend/lib/i486/Werkzeug-0.11.15-py3.4.egg-info/PKG-INFO \
    qml/backend/lib/i486/Werkzeug-0.11.15-py3.4.egg-info/SOURCES.txt \
    qml/backend/lib/i486/Werkzeug-0.11.15-py3.4.egg-info/top_level.txt \
    qml/backend/lib/i486/bs4/builder/__init__.py \
    qml/backend/lib/i486/bs4/builder/_html5lib.py \
    qml/backend/lib/i486/bs4/builder/_htmlparser.py \
    qml/backend/lib/i486/bs4/builder/_lxml.py \
    qml/backend/lib/i486/bs4/tests/__init__.py \
    qml/backend/lib/i486/bs4/tests/test_builder_registry.py \
    qml/backend/lib/i486/bs4/tests/test_docs.py \
    qml/backend/lib/i486/bs4/tests/test_html5lib.py \
    qml/backend/lib/i486/bs4/tests/test_htmlparser.py \
    qml/backend/lib/i486/bs4/tests/test_lxml.py \
    qml/backend/lib/i486/bs4/tests/test_soup.py \
    qml/backend/lib/i486/bs4/tests/test_tree.py \
    qml/backend/lib/i486/bs4/1631353.py \
    qml/backend/lib/i486/bs4/__init__.py \
    qml/backend/lib/i486/bs4/dammit.py \
    qml/backend/lib/i486/bs4/diagnose.py \
    qml/backend/lib/i486/bs4/element.py \
    qml/backend/lib/i486/bs4/testing.py \
    qml/backend/lib/i486/requests/packages/chardet/__init__.py \
    qml/backend/lib/i486/requests/packages/chardet/big5freq.py \
    qml/backend/lib/i486/requests/packages/chardet/big5prober.py \
    qml/backend/lib/i486/requests/packages/chardet/chardetect.py \
    qml/backend/lib/i486/requests/packages/chardet/chardistribution.py \
    qml/backend/lib/i486/requests/packages/chardet/charsetgroupprober.py \
    qml/backend/lib/i486/requests/packages/chardet/charsetprober.py \
    qml/backend/lib/i486/requests/packages/chardet/codingstatemachine.py \
    qml/backend/lib/i486/requests/packages/chardet/compat.py \
    qml/backend/lib/i486/requests/packages/chardet/constants.py \
    qml/backend/lib/i486/requests/packages/chardet/cp949prober.py \
    qml/backend/lib/i486/requests/packages/chardet/escprober.py \
    qml/backend/lib/i486/requests/packages/chardet/escsm.py \
    qml/backend/lib/i486/requests/packages/chardet/eucjpprober.py \
    qml/backend/lib/i486/requests/packages/chardet/euckrfreq.py \
    qml/backend/lib/i486/requests/packages/chardet/euckrprober.py \
    qml/backend/lib/i486/requests/packages/chardet/euctwfreq.py \
    qml/backend/lib/i486/requests/packages/chardet/euctwprober.py \
    qml/backend/lib/i486/requests/packages/chardet/gb2312freq.py \
    qml/backend/lib/i486/requests/packages/chardet/gb2312prober.py \
    qml/backend/lib/i486/requests/packages/chardet/hebrewprober.py \
    qml/backend/lib/i486/requests/packages/chardet/jisfreq.py \
    qml/backend/lib/i486/requests/packages/chardet/jpcntx.py \
    qml/backend/lib/i486/requests/packages/chardet/langbulgarianmodel.py \
    qml/backend/lib/i486/requests/packages/chardet/langcyrillicmodel.py \
    qml/backend/lib/i486/requests/packages/chardet/langgreekmodel.py \
    qml/backend/lib/i486/requests/packages/chardet/langhebrewmodel.py \
    qml/backend/lib/i486/requests/packages/chardet/langhungarianmodel.py \
    qml/backend/lib/i486/requests/packages/chardet/langthaimodel.py \
    qml/backend/lib/i486/requests/packages/chardet/latin1prober.py \
    qml/backend/lib/i486/requests/packages/chardet/mbcharsetprober.py \
    qml/backend/lib/i486/requests/packages/chardet/mbcsgroupprober.py \
    qml/backend/lib/i486/requests/packages/chardet/mbcssm.py \
    qml/backend/lib/i486/requests/packages/chardet/sbcharsetprober.py \
    qml/backend/lib/i486/requests/packages/chardet/sbcsgroupprober.py \
    qml/backend/lib/i486/requests/packages/chardet/sjisprober.py \
    qml/backend/lib/i486/requests/packages/chardet/universaldetector.py \
    qml/backend/lib/i486/requests/packages/chardet/utf8prober.py \
    qml/backend/lib/i486/requests/packages/idna/__init__.py \
    qml/backend/lib/i486/requests/packages/idna/codec.py \
    qml/backend/lib/i486/requests/packages/idna/compat.py \
    qml/backend/lib/i486/requests/packages/idna/core.py \
    qml/backend/lib/i486/requests/packages/idna/idnadata.py \
    qml/backend/lib/i486/requests/packages/idna/intranges.py \
    qml/backend/lib/i486/requests/packages/idna/uts46data.py \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/__init__.py \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/appengine.py \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/ntlmpool.py \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/pyopenssl.py \
    qml/backend/lib/i486/requests/packages/urllib3/contrib/socks.py \
    qml/backend/lib/i486/requests/packages/urllib3/packages/backports/__init__.py \
    qml/backend/lib/i486/requests/packages/urllib3/packages/backports/makefile.py \
    qml/backend/lib/i486/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py \
    qml/backend/lib/i486/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py \
    qml/backend/lib/i486/requests/packages/urllib3/packages/__init__.py \
    qml/backend/lib/i486/requests/packages/urllib3/packages/ordered_dict.py \
    qml/backend/lib/i486/requests/packages/urllib3/packages/six.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/__init__.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/connection.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/request.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/response.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/retry.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/selectors.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/ssl_.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/timeout.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/url.py \
    qml/backend/lib/i486/requests/packages/urllib3/util/wait.py \
    qml/backend/lib/i486/requests/packages/urllib3/__init__.py \
    qml/backend/lib/i486/requests/packages/urllib3/_collections.py \
    qml/backend/lib/i486/requests/packages/urllib3/connection.py \
    qml/backend/lib/i486/requests/packages/urllib3/connectionpool.py \
    qml/backend/lib/i486/requests/packages/urllib3/exceptions.py \
    qml/backend/lib/i486/requests/packages/urllib3/fields.py \
    qml/backend/lib/i486/requests/packages/urllib3/filepost.py \
    qml/backend/lib/i486/requests/packages/urllib3/poolmanager.py \
    qml/backend/lib/i486/requests/packages/urllib3/request.py \
    qml/backend/lib/i486/requests/packages/urllib3/response.py \
    qml/backend/lib/i486/requests/packages/__init__.py \
    qml/backend/lib/i486/requests/__init__.py \
    qml/backend/lib/i486/requests/_internal_utils.py \
    qml/backend/lib/i486/requests/adapters.py \
    qml/backend/lib/i486/requests/api.py \
    qml/backend/lib/i486/requests/auth.py \
    qml/backend/lib/i486/requests/certs.py \
    qml/backend/lib/i486/requests/compat.py \
    qml/backend/lib/i486/requests/cookies.py \
    qml/backend/lib/i486/requests/exceptions.py \
    qml/backend/lib/i486/requests/hooks.py \
    qml/backend/lib/i486/requests/models.py \
    qml/backend/lib/i486/requests/sessions.py \
    qml/backend/lib/i486/requests/status_codes.py \
    qml/backend/lib/i486/requests/structures.py \
    qml/backend/lib/i486/requests/utils.py \
    qml/backend/lib/i486/robobrowser/forms/__init__.py \
    qml/backend/lib/i486/robobrowser/forms/fields.py \
    qml/backend/lib/i486/robobrowser/forms/form.py \
    qml/backend/lib/i486/robobrowser/__init__.py \
    qml/backend/lib/i486/robobrowser/browser.py \
    qml/backend/lib/i486/robobrowser/cache.py \
    qml/backend/lib/i486/robobrowser/compat.py \
    qml/backend/lib/i486/robobrowser/exceptions.py \
    qml/backend/lib/i486/robobrowser/helpers.py \
    qml/backend/lib/i486/robobrowser/ordereddict.py \
    qml/backend/lib/i486/robobrowser/responses.py \
    qml/backend/lib/i486/werkzeug/contrib/__init__.py \
    qml/backend/lib/i486/werkzeug/contrib/atom.py \
    qml/backend/lib/i486/werkzeug/contrib/cache.py \
    qml/backend/lib/i486/werkzeug/contrib/fixers.py \
    qml/backend/lib/i486/werkzeug/contrib/iterio.py \
    qml/backend/lib/i486/werkzeug/contrib/jsrouting.py \
    qml/backend/lib/i486/werkzeug/contrib/limiter.py \
    qml/backend/lib/i486/werkzeug/contrib/lint.py \
    qml/backend/lib/i486/werkzeug/contrib/profiler.py \
    qml/backend/lib/i486/werkzeug/contrib/securecookie.py \
    qml/backend/lib/i486/werkzeug/contrib/sessions.py \
    qml/backend/lib/i486/werkzeug/contrib/testtools.py \
    qml/backend/lib/i486/werkzeug/contrib/wrappers.py \
    qml/backend/lib/i486/werkzeug/debug/__init__.py \
    qml/backend/lib/i486/werkzeug/debug/console.py \
    qml/backend/lib/i486/werkzeug/debug/repr.py \
    qml/backend/lib/i486/werkzeug/debug/tbtools.py \
    qml/backend/lib/i486/werkzeug/__init__.py \
    qml/backend/lib/i486/werkzeug/_compat.py \
    qml/backend/lib/i486/werkzeug/_internal.py \
    qml/backend/lib/i486/werkzeug/_reloader.py \
    qml/backend/lib/i486/werkzeug/datastructures.py \
    qml/backend/lib/i486/werkzeug/exceptions.py \
    qml/backend/lib/i486/werkzeug/filesystem.py \
    qml/backend/lib/i486/werkzeug/formparser.py \
    qml/backend/lib/i486/werkzeug/http.py \
    qml/backend/lib/i486/werkzeug/local.py \
    qml/backend/lib/i486/werkzeug/posixemulation.py \
    qml/backend/lib/i486/werkzeug/routing.py \
    qml/backend/lib/i486/werkzeug/script.py \
    qml/backend/lib/i486/werkzeug/security.py \
    qml/backend/lib/i486/werkzeug/serving.py \
    qml/backend/lib/i486/werkzeug/test.py \
    qml/backend/lib/i486/werkzeug/testapp.py \
    qml/backend/lib/i486/werkzeug/urls.py \
    qml/backend/lib/i486/werkzeug/useragents.py \
    qml/backend/lib/i486/werkzeug/utils.py \
    qml/backend/lib/i486/werkzeug/wrappers.py \
    qml/backend/lib/i486/werkzeug/wsgi.py \
    qml/backend/lib/i486/six.py \
    qml/pages/js/auth.js \
    qml/pages/NavigationBarDelegate.qml \
    rpm/harbour-sailfinder.changes \
    qml/pages/js/messages.js \
    qml/pages/js/gif.js \
    rpm/NOARCH_harbour-sailfinder.yaml \
    rpm/harbour-sailfinder.yaml \
    rpm/harbour-sailfinder.spec \
    qml/pages/GifGalleryPage.qml \
    qml/pages/AboutMatchPage.qml \
    qml/pages/js/updates.js
